name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # 3. Install Flutter dependencies
      - run: flutter pub get

      # 4. Fix velocity_x compatibility issue
      - name: Patch velocity_x
        run: |
          sed -i '' 's/CardThemeData/CardTheme/g' ~/.pub-cache/hosted/pub.dev/velocity_x-*/lib/src/flutter/universal.dart

      # 5. Update CocoaPods repository
      - run: pod repo update
        working-directory: ios

      # 6. Build iOS app (no code signing)
      - run: flutter build ios --release --no-codesign

      # 7. Create Payload directory
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      # 8. Move Runner.app into Payload
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # 9. Zip the output to create .ipa
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # 10. Upload .ipa to GitHub release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
